config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'calculator', to: 'pages#calculator', as: 'calculator'

  get 'articles', to: 'pages#articles', as: 'articles'

  get 'calculator/:hero', to: 'calculator#hero', as: 'hero'

  get 'about', to: 'pages#about', as: 'about'

  get 'articles/:article', to: 'articles#article', as: 'article'

  get 'admin78956789', to: 'pages#admin', as: 'admin'

  get 'admin78956789/news', to: 'pages#news_admin', as: 'news_admin'

  get 'admin78956789/news/create', to: 'news_admin#create_news', as: 'news_create'

  post 'admin78956789/news/create', to: 'news_admin#create', as: 'create_news'

  get 'admin78956789/news/update', to: 'news_admin#update_news', as: 'news_update'

  post 'admin78956789/news/update', to: 'news_admin#update', as: 'update_news'

  get 'admin78956789/:hero', to: 'heroes_admin#hero', as: 'admin_hero'

  post 'admin78956789/:hero', to: 'heroes_admin#update', as: 'update'

  get 'pages/home'

  get 'pages/contacts'

end

app/controllers/admin_controller.rb
class AdminController < PagesController

	def admin_hero
	end

	def update
		puts "METHOD UPDATE CALLED AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
		if @mongo_client == nil
			#uri = "mongodb://127.0.0.1:27017/test"
			uri = "mongodb://cherya:cherya123@ds141128.mlab.com:41128/heroku_82ppsrn9"
			@mongo_client = Mongo::Client.new(uri)
		end
		collection = @mongo_client[:heroes]
		puts "JSON #{JSON.parse(params[:hero_json])}"
		json = JSON.parse(params[:hero_json])
		hero_id = json['hero_id']
		collection.update_one( { 'hero_id' => hero_id }, {'$set' => json} )
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def mongo_client
  	#uri = "mongodb://127.0.0.1:27017/test"
  	uri = "mongodb://cherya:cherya123@ds141128.mlab.com:41128/heroku_82ppsrn9"
  	mongo_client = Mongo::Client.new(uri)
  end

end

app/controllers/articles_controller.rb
class ArticlesController < PagesController

	def article
		collection = mongo_client[:news]
		@article_to_display = collection.find( { id: params[:article] } ).first
	end

end

app/controllers/calculator_controller.rb
class CalculatorController < PagesController

	def hero
	end

end

app/controllers/heroes_admin_controller.rb
class HeroesAdminController < PagesController

	def admin_hero
	end

	def update
		puts "METHOD UPDATE CALLED AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
		collection = mongo_client[:heroes]
		puts "JSON #{JSON.parse(params[:hero_json])}"
		json = JSON.parse(params[:hero_json])
		hero_id = json['hero_id']
		collection.update_one( { 'hero_id' => hero_id }, {'$set' => json} )
	end
end

app/controllers/news_admin_controller.rb
class NewsAdminController < ApplicationController

	def admin_news
	end

	def create
		collection = mongo_client[:news]
		id = params[:id]
		main_image = params[:main_image]
		summary = params[:summary]
		content = params[:content]
		collection.insert_one( { id: id, main_image: main_image, summary: summary, content: content } )
	end

	def update
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def home
  end

  def contacts
  end

  def calculator
  end

  def articles
	collection = mongo_client[:news]
	@articles = collection.find
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def is_active?(link_path)
 		current_page?(link_path) ? "active" : ""
	end

    def is_calc_active?(link_path)
        params[:controller] == 'calculator' || current_page?(link_path) ? "active" : ""
    end

    def is_articles_active?(link_path)
        params[:controller] == 'articles' || current_page?(link_path) ? "active" : ""
    end

	def extends(layout, &block)
    # Make sure it's a string
    layout = layout.to_s

    # If there's no directory component, presume a plain layout name
    layout = "layouts/#{layout}" unless layout.include?('/')

    # Capture the content to be placed inside the extended layout
    @view_flow.get(:layout).replace capture(&block)

    render file: layout
  end
end

app/helpers/pages_helper.rb
require 'json'
require 'securerandom'

module PagesHelper
	
	def get_hero_name 
		url = request.original_url
		url.split('/').last.remove(/#.*\+*/)
	end

	def read_json
		hero_name = get_hero_name
		file = File.read("app/assets/jsons/#{hero_name}.json")
		JSON.parse(file)
	end	

	def get_json_from_mongo
		hero_name = get_hero_name
		if @mongo_client == nil
			#uri = "mongodb://127.0.0.1:27017/test"
			uri = "mongodb://cherya:cherya123@ds141128.mlab.com:41128/heroku_82ppsrn9"
			@mongo_client = Mongo::Client.new(uri)
		end
		collection = @mongo_client[:heroes]
		file = collection.find( {hero_id: "#{hero_name}"} ).first
		file.delete('_id')
		file
	end

	def hero_name
		data = get_json_from_mongo
		data['hero_name']
	end

	def hero_image
		data = get_json_from_mongo
		data['hero_image']
	end

	def talent_image(id)
		begin
		data = get_json_from_mongo
		data['talents'][id]['talent_image']
		rescue NoMethodError
		end
	end

	def generate_hero(name, image, link)
		content_tag(:a, '', class: 'hero', href: link) do 
			image_tag(image) +
			content_tag(:span, name)
      	end
	end

	def generate_random_id
	 	SecureRandom.hex
	end

	def generate_article(article)
			content_tag(:div, '', class: 'article') do 
			article_image(article) +  
			content_tag(:div, '', class: 'article_desc') do 
				content_tag(:a, article[:summary], class: 'article_summary', href: "articles/#{article[:id]}") +
				content_tag(:div, article[:content].html_safe, class: 'article_content')
			end
     	end
 	end

 	def article_image(article)
 		if article[:main_image] != '' 
 			return image_tag(article[:main_image], class: 'article_img') 
 		else
 			return content_tag(:div)
 		end
 	end

 	def display_article(article)
 		content_tag(:div, '', class: 'article_all') do 
			image_tag(article[:main_image], class: 'article_img_all') +
			content_tag(:div, '', class: 'article_desc') do 
				content_tag(:span, article[:summary], class: 'article_summary') +
				content_tag(:div, article[:content].html_safe, class: 'article_content_all')
			end
     	end
 	end
end

app/views/heroes_admin/update.html.erb
Hero Updated Succesfully.

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
<%= javascript_include_tag 'admin' %>
</head>
<body>
<%= content_tag :div, class: "temp_information", data: {temp: get_json_from_mongo} do %>
<% end %>
<%= form_tag do %>
  <%= text_area_tag 'hero_json', nil, size: "100x120"%>
  <%= submit_tag "Update",  :style => "vertical-align: top" %>
<% end %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-3466259882861893",
    enable_page_level_ads: true
  });
</script>
  <title>Agni Hots</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-87578114-1', 'auto');
  ga('send', 'pageview');

</script>
<body>

<!DOCTYPE html>
<!-- Template by Quackit.com -->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
</head>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Logo and responsive toggle -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "/#", :class => "navbar-brand" do %>
                    <span class="glyphicon glyphicon-fire"></span>
                    HotS
                <% end %>
            </div>
            <!-- Navbar links -->
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="nav navbar-nav">
                    <li class="<%= is_active?('/') %>"> 
                        <%= link_to "Главная", '/#' %>
                    </li>
                    <li class="<%= is_articles_active?(articles_path) %>"> 
                        <%= link_to "Статьи", articles_path %>
                    </li>
                    <li class="<%= is_calc_active?(calculator_path) %>">
                        <%= link_to "Калькулятор", calculator_path %>
                    </li>    
                    <li class="<%= is_active?(about_path) %>">
                        <%= link_to "Буст", about_path %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

<%= yield %>

</body>
<footer>   
         <div class="small-print">
           <div class="container">
               <p>Copyright &copy; metahots 2016 </p>
           </div>
         </div>
   </footer>
</html>

app/views/layouts/articles.html.erb
<%= extends :application do %>
<html>
<body>
<div class="jumbotron feature">
	<div class="container">
		<%= display_article(@article_to_display) %>
	</div>
</div>
</body>
</html>
<% end %>

app/views/layouts/calculator.html.erb
<%= extends :application do %>
<html>
	<head><%= javascript_include_tag 'application' %></head>
	<div class="calculator">
		<%= content_tag :div, class: "temp_information", data: {temp: get_json_from_mongo} do %>
		<% end %>
		<div style="position:relative;">
		<h1 class="hero"><%= hero_name %></h1>
		<img class="hero" src="<%= hero_image %>"/>
		<button class="btn btn-default" style="position: absolute; bottom: 0px; margin: 10px;" onclick="showBuild()">Билд by Agni.</button>
		</div>
		<div id="lvl1" class="level">
			<label for="lvl1" class="level">1</label>
			<form action="#" method="post">
				<img id="l1t1" class="talent" name="l1" src="<%= talent_image('l1t1') %>" onclick="showText('l1_name', 'l1_description', this.id); showComment('l1_comment_title', 'l1_comment_desc', this.id); jumpto(this.id + '+')" />
				<img id="l1t2" class="talent" name="l1" src="<%= talent_image('l1t2') %>" onclick="showText('l1_name', 'l1_description', this.id); showComment('l1_comment_title', 'l1_comment_desc', this.id); jumpto(this.id + '+')" />
				<img id="l1t3" class="talent" name="l1" src="<%= talent_image('l1t3') %>" onclick="showText('l1_name', 'l1_description', this.id); showComment('l1_comment_title', 'l1_comment_desc', this.id); jumpto(this.id + '+')" />
				<img id="l1t4" class="talent" name="l1" src="<%= talent_image('l1t4') %>" onclick="showText('l1_name', 'l1_description', this.id); showComment('l1_comment_title', 'l1_comment_desc', this.id); jumpto(this.id + '+')" />
			</form>
			<div class="talent-description">
				<span class="talent-title" id="l1_name" style="font-weight: bold"></span>
				<span class="talent-desc" id="l1_description"></span>
			</div>
			<div class="comment">
				<span class="talent-title" id="l1_comment_title" style="font-weight: bold"></span>
				<span class="talent-desc" id="l1_comment_desc"></span>
			</div>
		</div>
		<div id="lvl4" class="level">
			<label for="lvl4" class="level">4</label>
			<form action="#" method="post">
				<img id="l4t1" class="talent" name="l4" src="<%= talent_image('l4t1') %>" onclick="showText('l4_name', 'l4_description', this.id); jumpto(this.id + '+'); showComment('l4_comment_title', 'l4_comment_desc', this.id)" />
				<img id="l4t2" class="talent" name="l4" src="<%= talent_image('l4t2') %>" onclick="showText('l4_name', 'l4_description', this.id); jumpto(this.id + '+'); showComment('l4_comment_title', 'l4_comment_desc', this.id)" />
				<img id="l4t3" class="talent" name="l4" src="<%= talent_image('l4t3') %>" onclick="showText('l4_name', 'l4_description', this.id); jumpto(this.id + '+'); showComment('l4_comment_title', 'l4_comment_desc', this.id)" />
				<img id="l4t4" class="talent" name="l4" src="<%= talent_image('l4t4') %>" onclick="showText('l4_name', 'l4_description', this.id); jumpto(this.id + '+'); showComment('l4_comment_title', 'l4_comment_desc', this.id)" />
				<img id="l4t5" class="talent" name="l4" src="<%= talent_image('l4t5') %>" onclick="showText('l4_name', 'l4_description', this.id); jumpto(this.id + '+'); showComment('l4_comment_title', 'l4_comment_desc', this.id)" />
			</form>
			<div class="talent-description">
				<span class="talent-title" id="l4_name" style="font-weight: bold"></span>
				<span class="talent-desc" id="l4_description"></span>
			</div>
			<div class="comment">
				<span class="talent-title" id="l4_comment_title" style="font-weight: bold"></span>
				<span class="talent-desc" id="l4_comment_desc"></span>
			</div>
		</div>
		<div id="lvl7" class="level">
			<label for="lvl7" class="level">7</label>
			<form action="#" method="post">
				<img id="l7t1" class="talent" name="l7" src="<%= talent_image('l7t1') %>" onclick="showText('l7_name', 'l7_description', this.id); jumpto(this.id + '+'); showComment('l7_comment_title', 'l7_comment_desc', this.id)" />

				<img id="l7t2" class="talent" name="l7" src="<%= talent_image('l7t2') %>" onclick="showText('l7_name', 'l7_description', this.id); jumpto(this.id + '+'); showComment('l7_comment_title', 'l7_comment_desc', this.id)" />

				<img id="l7t3" class="talent" name="l7" src="<%= talent_image('l7t3') %>" onclick="showText('l7_name', 'l7_description', this.id); jumpto(this.id + '+'); showComment('l7_comment_title', 'l7_comment_desc', this.id)" />
				<img id="l7t4" class="talent" name="l7" src="<%= talent_image('l7t4') %>" onclick="showText('l7_name', 'l7_description', this.id); jumpto(this.id + '+'); showComment('l7_comment_title', 'l7_comment_desc', this.id)" />
			</form>
			<div class="talent-description">
				<span class="talent-title" id="l7_name" style="font-weight: bold"></span>
				<span class="talent-desc" id="l7_description"></span>
			</div>
			<div class="comment">
				<span class="talent-title" id="l7_comment_title" style="font-weight: bold"></span>
				<span class="talent-desc" id="l7_comment_desc"></span>
			</div>
		</div>	
		<div id="lvl10" class="level">
			<label for="lvl10" class="level">10</label>
			<form action="#" method="post">
				<img id="l10t1" class="talent" name="l10" src="<%= talent_image('l10t1') %>" onclick="showText('l10_name', 'l10_description', this.id); jumpto(this.id + '+'); showComment('l10_comment_title', 'l10_comment_desc', this.id)" />
				<img id="l10t2" class="talent" name="l10" src="<%= talent_image('l10t2') %>" onclick="showText('l10_name', 'l10_description', this.id); jumpto(this.id + '+'); showComment('l10_comment_title', 'l10_comment_desc', this.id)" />
				<img id="l10t3" class="talent" name="l10" src="<%= talent_image('l10t3') %>" onclick="showText('l10_name', 'l10_description', this.id); jumpto(this.id + '+'); showComment('l10_comment_title', 'l10_comment_desc', this.id)" />
			</form>
			<div class="talent-description">
				<span class="talent-title" id="l10_name" style="font-weight: bold"></span>
				<span class="talent-desc" id="l10_description"></span>
			</div>
			<div class="comment">
				<span class="talent-title" id="l10_comment_title" style="font-weight: bold"></span>
				<span class="talent-desc" id="l10_comment_desc"></span>
			</div>
		</div>
		<div id="lvl13" class="level">
			<label for="lvl13" class="level">13</label>
			<form action="#" method="post">
				<img id="l13t1" class="talent" name="l13" src="<%= talent_image('l13t1') %>" onclick="showText('l13_name', 'l13_description', this.id); jumpto(this.id + '+'); showComment('l13_comment_title', 'l13_comment_desc', this.id)" />
				<img id="l13t2" class="talent" name="l13" src="<%= talent_image('l13t2') %>" onclick="showText('l13_name', 'l13_description', this.id); jumpto(this.id + '+'); showComment('l13_comment_title', 'l13_comment_desc', this.id)" />
				<img id="l13t3" class="talent" name="l13" src="<%= talent_image('l13t3') %>" onclick="showText('l13_name', 'l13_description', this.id); jumpto(this.id + '+'); showComment('l13_comment_title', 'l13_comment_desc', this.id)" />
				<img id="l13t4" class="talent" name="l13" src="<%= talent_image('l13t4') %>" onclick="showText('l13_name', 'l13_description', this.id); jumpto(this.id + '+'); showComment('l13_comment_title', 'l13_comment_desc', this.id)" />
			</form>
			<div class="talent-description">
				<span class="talent-title" id="l13_name" style="font-weight: bold"></span>
				<span class="talent-desc" id="l13_description"></span>
			</div>
			<div class="comment">
				<span class="talent-title" id="l13_comment_title" style="font-weight: bold"></span>
				<span class="talent-desc" id="l13_comment_desc"></span>
			</div>
		</div>
		<div id="lvl16" class="level">
			<label for="lvl16" class="level">16</label>
			<form action="#" method="post">
				<img id="l16t1" class="talent" name="l16" src="<%= talent_image('l16t1') %>" onclick="showText('l16_name', 'l16_description', this.id); jumpto(this.id + '+'); showComment('l16_comment_title', 'l16_comment_desc', this.id)" />
				<img id="l16t2" class="talent" name="l16" src="<%= talent_image('l16t2') %>" onclick="showText('l16_name', 'l16_description', this.id); jumpto(this.id + '+'); showComment('l16_comment_title', 'l16_comment_desc', this.id)" />
				<img id="l16t3" class="talent" name="l16" src="<%= talent_image('l16t3') %>" onclick="showText('l16_name', 'l16_description', this.id); jumpto(this.id + '+'); showComment('l16_comment_title', 'l16_comment_desc', this.id)" />
				<img id="l16t4" class="talent" name="l16" src="<%= talent_image('l16t4') %>" onclick="showText('l16_name', 'l16_description', this.id); jumpto(this.id + '+'); showComment('l16_comment_title', 'l16_comment_desc', this.id)" />
				<img id="l16t5" class="talent" name="l16" src="<%= talent_image('l16t5') %>" onclick="showText('l16_name', 'l16_description', this.id); jumpto(this.id + '+'); showComment('l16_comment_title', 'l16_comment_desc', this.id)" />
			</form>
			<div class="talent-description">
				<span class="talent-title" id="l16_name" style="font-weight: bold"></span>
				<span class="talent-desc" id="l16_description"></span>
			</div>
			<div class="comment">
				<span class="talent-title" id="l16_comment_title" style="font-weight: bold"></span>
				<span class="talent-desc" id="l16_comment_desc"></span>
			</div>
		</div>
		<div id="lvl20" class="level">
			<label for="lvl20" class="level">20</label>
			<form action="#" method="post">
				<img id="l20t1" class="talent" name="l20" src="<%= talent_image('l20t1') %>" onclick="showText('l20_name', 'l20_description', this.id); jumpto(this.id + '+'); showComment('l20_comment_title', 'l20_comment_desc', this.id)" />
				<img id="l20t2" class="talent" name="l20" src="<%= talent_image('l20t2') %>" onclick="showText('l20_name', 'l20_description', this.id); jumpto(this.id + '+'); showComment('l20_comment_title', 'l20_comment_desc', this.id)" />
				<img id="l20t3" class="talent" name="l20" src="<%= talent_image('l20t3') %>" onclick="showText('l20_name', 'l20_description', this.id); jumpto(this.id + '+'); showComment('l20_comment_title', 'l20_comment_desc', this.id)" />
				<img id="l20t4" class="talent" name="l20" src="<%= talent_image('l20t4') %>" onclick="showText('l20_name', 'l20_description', this.id); jumpto(this.id + '+'); showComment('l20_comment_title', 'l20_comment_desc', this.id)" />
				<img id="l20t5" class="talent" name="l20" src="<%= talent_image('l20t5') %>" onclick="showText('l20_name', 'l20_description', this.id); jumpto(this.id + '+'); showComment('l20_comment_title', 'l20_comment_desc', this.id)" />
			</form>
			<div class="talent-description">
				<span class="talent-title" id="l20_name" style="font-weight: bold"></span>
				<span class="talent-desc" id="l20_description"></span>
			</div>
			<div class="comment">
				<span class="talent-title" id="l20_comment_title" style="font-weight: bold"></span>
				<span class="talent-desc" id="l20_comment_desc"></span>
			</div>
		</div>
	</div>
</html>
<% end %>

app/views/layouts/heroes_admin.html.erb
<!DOCTYPE html>
<html>
<head>
<%= javascript_include_tag 'admin' %>
</head>
<body>
<%= content_tag :div, class: "temp_information", data: {temp: get_json_from_mongo} do %>
<% end %>
<%= form_tag do %>
  <%= text_area_tag 'hero_json', nil, size: "100x120"%>
  <%= submit_tag "Update",  :style => "vertical-align: top" %>
<% end %>
</body>
</html>

app/views/news_admin/create.html.erb
CREATED

app/views/news_admin/create_news.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<%= content_tag :div do %>
<% end %>
<%= form_tag do %>
  <%= label_tag 'id', 'ID:', class: 'admin_label' %>
  <%= text_area_tag 'id', generate_random_id, size: "50x5" %>
  <%= label_tag 'main_image', 'Картинка:', class: 'admin_label' %>
  <%= text_area_tag 'main_image', nil, size: "50x5" %>
  <%= label_tag 'summary', 'Название:', class: 'admin_label' %>
  <%= text_area_tag 'summary', nil, size: "50x5" %>
  <%= label_tag 'content', 'Контент:', class: 'admin_label' %>
  <%= text_area_tag 'content', nil, size: "120x20" %>
  <%= submit_tag "Create" %>
<% end %>
</body>
</html>

app/views/news_admin/update.html.erb
UPDATE

app/views/news_admin/update_news.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<%= content_tag :div do %>
<% end %>
<%= form_tag do %>
  <%= text_area_tag 'main_image', nil, size: "5x50"%>
  <%= text_area_tag 'content', nil, size: "10x30"%>
  <%= submit_tag "Create" %>
<% end %>
</body>
</html>

app/views/pages/about.html.erb
<html>
<body>
<div class="jumbotron feature">
	<div class="container">
		<h1>Буст</h1>
		<p>Контакт через vk: <a href='https://vk.com/agni_agni'>agni_agni</a></p>
		<div>
		<p><b>Все цены указаны за один дивизион (это одна цифра): </b></p>

		<p>Алмаз - 1000р</p>
		<p>Платина - 700р</p>
		<p>Золото - 500р </p>
		<p>Серебро - 400р </p>
		<p>Бронза 300р </p>

		<p>1 поинт в мастере - 3р</p>

		<p>Калибровка - 1300р</p>

		<p>Повторы игр - 300р</p>

		<p><i>Оплата на киви</i></p>
</div>
	</div>
</div>
</body>
</html>

app/views/pages/articles.html.erb
<html>
<body>
<div class="jumbotron feature">
	<div class="container">
		<h1>Статьи</h1>
		<% @articles.each do |article| %>
   			<%= generate_article(article) %>
		<%end %>
	</div>
</div>
</body>
</html>

app/views/pages/contacts.html.erb
<h1>Pages#contacts</h1>
<p>Find me in app/views/pages/contacts.html.erb</p>

app/views/pages/home.html.erb
<!DOCTYPE html>
<!-- Template by Quackit.com -->
<html lang="en">

    <div class="jumbotron feature">
        <div class="container">
            <h1><span class="glyphicon glyphicon-fire">Agni.</span>
            <iframe src="https://player.twitch.tv/?channel=agni_agni&autoplay=false" frameborder="0" scrolling="no" height="330" width="580" align="right"></iframe></h1>
            <a target="_blank" class="btn btn-default" href="https://www.twitch.tv/agni_agni">Смотреть на twitch.tv</a>
        </div>
    </div>
</body>

</html>

app/views/pages/news_admin.html.erb
<html>
<a href='news/create'>Create</a>